/** Curated country list (ISO 3166-1 alpha-2) for onboarding. */
export const ONBOARDING_COUNTRIES: { code: string; name: string }[] = [
	{ code: 'AU', name: 'Australia' },
	{ code: 'AT', name: 'Austria' },
	{ code: 'BE', name: 'Belgium' },
	{ code: 'BR', name: 'Brazil' },
	{ code: 'CA', name: 'Canada' },
	{ code: 'CN', name: 'China' },
	{ code: 'CZ', name: 'Czech Republic' },
	{ code: 'DK', name: 'Denmark' },
	{ code: 'FI', name: 'Finland' },
	{ code: 'FR', name: 'France' },
	{ code: 'DE', name: 'Germany' },
	{ code: 'HK', name: 'Hong Kong' },
	{ code: 'IN', name: 'India' },
	{ code: 'IE', name: 'Ireland' },
	{ code: 'IT', name: 'Italy' },
	{ code: 'JP', name: 'Japan' },
	{ code: 'MY', name: 'Malaysia' },
	{ code: 'MX', name: 'Mexico' },
	{ code: 'NL', name: 'Netherlands' },
	{ code: 'NZ', name: 'New Zealand' },
	{ code: 'NO', name: 'Norway' },
	{ code: 'PL', name: 'Poland' },
	{ code: 'SG', name: 'Singapore' },
	{ code: 'ZA', name: 'South Africa' },
	{ code: 'KR', name: 'South Korea' },
	{ code: 'ES', name: 'Spain' },
	{ code: 'SE', name: 'Sweden' },
	{ code: 'CH', name: 'Switzerland' },
	{ code: 'TW', name: 'Taiwan' },
	{ code: 'TH', name: 'Thailand' },
	{ code: 'AE', name: 'United Arab Emirates' },
	{ code: 'GB', name: 'United Kingdom' },
	{ code: 'US', name: 'United States' }
];

/** Default currency + IANA timezone when a country is first selected. */
export const ONBOARDING_COUNTRY_DEFAULTS: Record<string, { currency: string; timezone: string }> = {
	AU: { currency: 'AUD', timezone: 'Australia/Sydney' },
	AT: { currency: 'EUR', timezone: 'Europe/Vienna' },
	BE: { currency: 'EUR', timezone: 'Europe/Brussels' },
	BR: { currency: 'BRL', timezone: 'America/Sao_Paulo' },
	CA: { currency: 'CAD', timezone: 'America/Toronto' },
	CN: { currency: 'CNY', timezone: 'Asia/Shanghai' },
	CZ: { currency: 'CZK', timezone: 'Europe/Prague' },
	DK: { currency: 'DKK', timezone: 'Europe/Copenhagen' },
	FI: { currency: 'EUR', timezone: 'Europe/Helsinki' },
	FR: { currency: 'EUR', timezone: 'Europe/Paris' },
	DE: { currency: 'EUR', timezone: 'Europe/Berlin' },
	HK: { currency: 'HKD', timezone: 'Asia/Hong_Kong' },
	IN: { currency: 'INR', timezone: 'Asia/Kolkata' },
	IE: { currency: 'EUR', timezone: 'Europe/Dublin' },
	IT: { currency: 'EUR', timezone: 'Europe/Rome' },
	JP: { currency: 'JPY', timezone: 'Asia/Tokyo' },
	MY: { currency: 'MYR', timezone: 'Asia/Kuala_Lumpur' },
	MX: { currency: 'MXN', timezone: 'America/Mexico_City' },
	NL: { currency: 'EUR', timezone: 'Europe/Amsterdam' },
	NZ: { currency: 'NZD', timezone: 'Pacific/Auckland' },
	NO: { currency: 'NOK', timezone: 'Europe/Oslo' },
	PL: { currency: 'PLN', timezone: 'Europe/Warsaw' },
	SG: { currency: 'SGD', timezone: 'Asia/Singapore' },
	ZA: { currency: 'ZAR', timezone: 'Africa/Johannesburg' },
	KR: { currency: 'KRW', timezone: 'Asia/Seoul' },
	ES: { currency: 'EUR', timezone: 'Europe/Madrid' },
	SE: { currency: 'SEK', timezone: 'Europe/Stockholm' },
	CH: { currency: 'CHF', timezone: 'Europe/Zurich' },
	TW: { currency: 'TWD', timezone: 'Asia/Taipei' },
	TH: { currency: 'THB', timezone: 'Asia/Bangkok' },
	AE: { currency: 'AED', timezone: 'Asia/Dubai' },
	GB: { currency: 'GBP', timezone: 'Europe/London' },
	US: { currency: 'USD', timezone: 'America/New_York' }
};

/** Common currencies for the currency dropdown. */
export const ONBOARDING_CURRENCIES: { code: string; label: string }[] = [
	{ code: 'USD', label: 'US Dollar' },
	{ code: 'EUR', label: 'Euro' },
	{ code: 'GBP', label: 'British Pound' },
	{ code: 'PLN', label: 'Polish Zloty' },
	{ code: 'AUD', label: 'Australian Dollar' },
	{ code: 'NZD', label: 'New Zealand Dollar' },
	{ code: 'CAD', label: 'Canadian Dollar' },
	{ code: 'CHF', label: 'Swiss Franc' },
	{ code: 'SEK', label: 'Swedish Krona' },
	{ code: 'NOK', label: 'Norwegian Krone' },
	{ code: 'DKK', label: 'Danish Krone' },
	{ code: 'CZK', label: 'Czech Koruna' },
	{ code: 'JPY', label: 'Japanese Yen' },
	{ code: 'SGD', label: 'Singapore Dollar' },
	{ code: 'HKD', label: 'Hong Kong Dollar' },
	{ code: 'INR', label: 'Indian Rupee' },
	{ code: 'ZAR', label: 'South African Rand' },
	{ code: 'BRL', label: 'Brazilian Real' },
	{ code: 'MXN', label: 'Mexican Peso' },
	{ code: 'CNY', label: 'Chinese Yuan' },
	{ code: 'KRW', label: 'South Korean Won' },
	{ code: 'MYR', label: 'Malaysian Ringgit' },
	{ code: 'THB', label: 'Thai Baht' },
	{ code: 'AED', label: 'UAE Dirham' },
	{ code: 'TWD', label: 'New Taiwan Dollar' }
];

/** IANA zones with short labels (subset). */
export const ONBOARDING_TIMEZONES: { value: string; label: string }[] = [
	{ value: 'Pacific/Auckland', label: '(UTC+12/+13) New Zealand' },
	{ value: 'Australia/Sydney', label: '(UTC+10/+11) Sydney, Melbourne' },
	{ value: 'Asia/Singapore', label: '(UTC+8) Singapore' },
	{ value: 'Asia/Hong_Kong', label: '(UTC+8) Hong Kong' },
	{ value: 'Asia/Tokyo', label: '(UTC+9) Japan' },
	{ value: 'Asia/Seoul', label: '(UTC+9) Korea' },
	{ value: 'Asia/Shanghai', label: '(UTC+8) China' },
	{ value: 'Asia/Kolkata', label: '(UTC+5:30) India' },
	{ value: 'Asia/Dubai', label: '(UTC+4) Dubai' },
	{ value: 'Europe/London', label: '(UTC+0/+1) United Kingdom' },
	{ value: 'Europe/Paris', label: '(UTC+1/+2) Paris, Berlin, Madrid' },
	{ value: 'Europe/Warsaw', label: '(UTC+1/+2) Warsaw, Sarajevo, Zagreb' },
	{ value: 'Europe/Stockholm', label: '(UTC+1/+2) Stockholm' },
	{ value: 'Europe/Amsterdam', label: '(UTC+1/+2) Amsterdam' },
	{ value: 'Europe/Zurich', label: '(UTC+1/+2) Switzerland' },
	{ value: 'Europe/Prague', label: '(UTC+1/+2) Prague' },
	{ value: 'Europe/Athens', label: '(UTC+2/+3) Athens' },
	{ value: 'America/New_York', label: '(UTC-5/-4) US Eastern' },
	{ value: 'America/Chicago', label: '(UTC-6/-5) US Central' },
	{ value: 'America/Denver', label: '(UTC-7/-6) US Mountain' },
	{ value: 'America/Los_Angeles', label: '(UTC-8/-7) US Pacific' },
	{ value: 'America/Toronto', label: '(UTC-5/-4) Toronto' },
	{ value: 'America/Mexico_City', label: '(UTC-6/-5) Mexico' },
	{ value: 'America/Sao_Paulo', label: '(UTC-3) Brazil' },
	{ value: 'UTC', label: '(UTC+0) UTC' }
];

export const ONBOARDING_INDUSTRIES: string[] = [
	'Accounting and bookkeeping',
	'Agriculture',
	'Construction',
	'Consulting',
	'Design',
	'E-commerce',
	'Education',
	'Engineering',
	'Entertainment',
	'Financial services',
	'Food and beverage',
	'Healthcare',
	'Hospitality',
	'Information technology',
	'Legal services',
	'Manufacturing',
	'Marketing and advertising',
	'Media',
	'Non-profit',
	'Professional services',
	'Real estate',
	'Retail',
	'Software',
	'Trades and services',
	'Transport and logistics',
	'Wholesale'
];

export const ONBOARDING_ACCOUNTING_TOOLS: { value: string; label: string }[] = [
	{ value: '', label: 'Select a tool' },
	{ value: 'NONE', label: 'None' },
	{ value: 'EXCEL', label: 'Spreadsheets (e.g. Excel)' },
	{ value: 'QUICKBOOKS', label: 'QuickBooks' },
	{ value: 'SAGE', label: 'Sage' },
	{ value: 'MYOB', label: 'MYOB' },
	{ value: 'WAVE', label: 'Wave' },
	{ value: 'FRESHBOOKS', label: 'FreshBooks' },
	{ value: 'OTHER', label: 'Other' }
];

export const MONTH_NAMES: { value: number; label: string }[] = [
	{ value: 1, label: 'January' },
	{ value: 2, label: 'February' },
	{ value: 3, label: 'March' },
	{ value: 4, label: 'April' },
	{ value: 5, label: 'May' },
	{ value: 6, label: 'June' },
	{ value: 7, label: 'July' },
	{ value: 8, label: 'August' },
	{ value: 9, label: 'September' },
	{ value: 10, label: 'October' },
	{ value: 11, label: 'November' },
	{ value: 12, label: 'December' }
];

export const FY_DAYS = Array.from({ length: 31 }, (_, i) => i + 1);
