-- +goose Up
-- +goose StatementBegin
-- Refresh tokens are opaque (not JWTs) so we can revoke them.  The raw token
-- is generated by the server (32 random bytes → base64url) and returned to
-- the client **once**; only its SHA-256 digest is persisted.  A client with
-- the raw string can exchange it at `POST /api/auth/refresh` for a new
-- access+refresh pair (rotation).
--
-- `revoked_at` is set when the token is rotated (happy path) or when reuse
-- of an already-revoked token is detected — the latter is an attack signal
-- and causes `replaced_by_id` chains to be fully revoked for that user.
CREATE TABLE refresh_tokens (
    token_id       UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id        UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    token_hash     CHAR(64) NOT NULL,               -- sha256 hex of the raw token
    issued_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at     TIMESTAMPTZ NOT NULL,
    revoked_at     TIMESTAMPTZ,
    replaced_by_id UUID REFERENCES refresh_tokens(token_id) ON DELETE SET NULL,
    user_agent     VARCHAR(500),
    ip             VARCHAR(64)
);

CREATE UNIQUE INDEX uq_refresh_tokens_hash ON refresh_tokens(token_hash);
CREATE INDEX idx_refresh_tokens_user      ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_expires   ON refresh_tokens(expires_at);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS refresh_tokens;
-- +goose StatementEnd
